baseurl = "https://PIControlLab.github.io/"
title = "GA-lab"
theme = "cleanwhite"
languageCode = "zh-us"
preserveTaxonomyNames = true
hasCJKLanguage = true

[services]
  # Enable comments by entering your Disqus shortname
  [services.disqus]
    shortname = ""
  [services.googleAnalytics]
    id = ""


[pagination]
  pagerSize = 10 # 每页显示文章数量

[outputs]
home = ["HTML", "RSS", "JSON"]
#home = ["HTML", "RSS"]

[params]
  custom_css = ["css/custom.css"]
  header_image = "/img/1681122792748811.jpg"
  banner_title = "通用智能体控制与决策实验室"
  SEOTitle = "BIT通用智能体控制与决策实验室"
  description = "这里是北京理工大学自动化学院通用智能体控制与决策实验室，欢迎前来交流。"
  keyword = "BIT, 北京理工大学, 北理工自动化学院 , GA-lab, 协同智能体通用探索实验室, 实验室,Generalized Agents Control and Decision Lab"
  slogan = "Generalized Agents Control and Decision Lab"
  upstreamAttribution = true

  local_search = true

  contact = "samyasa@qq.com"
  icp = "京ICP备12345678号"
  image_404 = "img/404-bg.jpg"
  title_404 = "你来到了没有知识的荒原 :("
  omit_categories = false

  # leancloud storage for page view counter
  page_view_counter = false
  leancloud_app_id = ""
  leancloud_app_key = ""

  # algolia site search
  algolia_search = false
  algolia_appId = ""
  algolia_indexName = ""
  algolia_apiKey = ""

  # Sidebar settings
  sidebar_about_description = "Software Developer, Open Source Enthusiast and Life Adventurer"
  #sidebar_avatar = "img/avatar-zhaohuabing.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`
  sidebar_avatar = "img/zhaohuabing.png"      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = true 
  featured_condition_size = 1 

  # Baidu Analytics
  ba_track_id = ""
  
  # We need a proxy to access Disqus api in China
  # Follow https://github.com/zhaohuabing/disqus-php-api to set up your own disqus proxy
  disqus_proxy = ""
  disqus_site = ""

  # Twikoo comments
  # Follow https://twikoo.js.org/ to set up your own env_id
  twikoo_env_id = ""

  # Artalk comments
  # Follow https://artalk.js.org/ to set up your own server
  artalk_enable = true
  artalk_server = "https://xxx.xxx.com"
  artalk_site = "xxx blog"

  #Enable wechat pay & alipay to allow readers send reward money if they like the articles 
  reward = true 
  # reward_guide = "如果这篇文章对你有用,请随意打赏" 

  friends = true
  bookmarks = false
  about_me = true

  # Last posts
  last_posts = true
  #last_posts_title = "LAST POSTS"
  #last_posts_count = 5

  # Include any custom CSS and/or JS files, url or relative to /static folder
  #custom_css = ["css/lightbox.css", "https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css", "css/main.css"]
  #custom_js = ["js/lightbox.js", "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js", "js/main.js"]

  [params.social]
  #rss            = true 
  #email          = "youremail@gmail.com"
  #facebook      = "full profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  #twitter       = "full profile url in twitter"
  #linkedin       = "https://www.linkedin.com/in/yourlinkedinid"
  #stackoverflow  = "https://stackoverflow.com/users/yourstackoverflowid"
  #instagram     = "full profile url in instagram"
  #github         = "https://github.com/yourgithub"
  #wechat         = "your wechat qr code image"
  #medium        = "full profile url in medium"
  #slack         = "full workspace url in slack"
  #pinterest     = "full profile url in pinterest"
  #reddit        = "full profile url in reddit"
  #gitlab        = "full profile url in gitlab"
  #mastodon      = "full profile url in mastodon"
  #keybase       = "full profile url in keybase"
  #xing          = "https://www.xing.com/profile/yourxingid"
  #git           = "full profile url for git user"
  
  [[params.friend_link]]
  title = "Linda的博客"
  href =  "https://zhaozhihan.com"

  [[params.bookmark_link]]
  title =  "Martin Fowler"
  href =  "https://martinfowler.com"
  [[params.bookmark_link]]
  title = "ServiceMesher"
  href =  "http://www.servicemesher.com"
  [[params.bookmark_link]]
  title =  "Pxhere"
  href = "https://pxhere.com"
  [[params.bookmark_link]]
  title = "unsplash"
  href = "https://unsplash.com"
  
  
  [[params.additional_menus]]
  title =  "新闻"
  href =  "/news/"
  [[params.additional_menus]]
  title =  "成员"
  href =  "/member/"
  [[params.additional_menus]]
  title =  "研究"
  href =  "/research/"
  [[params.additional_menus]]
  title =  "项目 "
  href =  "/projects/"
  [[params.additional_menus]]
  title =  "论文"
  href =  "/papers/"
  [[params.additional_menus]]
  title =  "展示"
  href =  "/gallery/"


[outputFormats]
  [outputFormats.JSON]
    baseName = "searchindex"
    mediaType = "application/json"
    isPlainText = true

#[outputFormats.Algolia]
#baseName = "algolia"
#isPlainText = true
#mediaType = "application/json"
#notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink", "content", "role", "position", "research", "email", "office", "phone", "authors", "venue", "abstract", "keywords", "doi", "year", "journal", "conference"]
params = ["categories", "tags", "experience", "projects", "papers", "volume", "issue", "pages"]

[markup]
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 1
  [markup.highlight]
    style = "dracula"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[mediaTypes]
  [mediaTypes.'font/woff']
    suffixes = ['woff']
  [mediaTypes.'font/woff2']
    suffixes = ['woff2']
